# Generated by Django 2.1.2 on 2018-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181027_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='descripcion',
            field=models.CharField(default='Null', max_length=100),
        ),
    ]
