# Generated by Django 2.1.2 on 2018-10-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_perro_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
